FROM node:20-alpine
WORKDIR /app
COPY frontend/package.json frontend/package-lock.json* frontend/yarn.lock* ./
RUN npm install --legacy-peer-deps || yarn install || true
COPY frontend /app
EXPOSE 3000
CMD ["npm", "run", "dev"]
